channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=0.35
- nodejs=8.9
- notebook=5.7
- tornado=5.1.1
- nbconvert=5.4
- widgetsnbextension=3.4
# Python Kernel
- ipykernel=5.1
- ipywidgets=7.4
- ipyleaflet=0.9
- altair=1.2
- bqplot=0.11.5
- dask=0.15
- matplotlib=3.1.0
- pandas=0.24
- python=3.6
- scikit-image=0.13
- scikit-learn=0.19
- seaborn=0.7
- tensorflow=1.1
- sympy=1.0
- pyyaml
- traittypes==0.2.1
- invoke=0.21
# C++ Kernel
- xeus-cling=0.5.1
- xtensor=0.20.7
- xtensor-blas=0.16.1
- xwidgets=0.17.0
- xleaflet=0.7.0
# R Kernel
- r-ggplot2
- r-irkernel=0.8.15
