name: yutianc-data-environment
channels:
  - damianavila82
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - bokeh
  - plotly
  - rise
  - ipywidgets
  - jupyter_contrib_nbextensions
